theme: jekyll-theme-slate
title: Александр
description: Data Analytics

defaults:
  - scope:
      path: ""
    values:
      layout: default

navigation:
  - title: Обо мне (RU)
    url: /about_ru/
  - title: Портфолио Аналитика Данных (RU)
    url: /portfolioDA_ru/    
  - title: Портфолио Дата-сайентиста (RU)
    url: /portfolioDS_ru/  

sass:
  style: compressed
  sass_dir: assets/css   #  явное указание папки
