theme: jekyll-theme-slate
title: Alex
description: DDData Analytics · BBBI · DDData Engineering

defaults:
  - scope:
      path: ""
    values:
      layout: default

navigation:
  - title: Обо мне (RU)
    url: /about_ru/
  - title: Портфолио Аналитика Данных (RU)
    url: /portfolioDA_ru/    
  - title: Портфолио Дата-сайентиста (RU)
    url: /portfolioDS_ru/  
